# Configurazione Render per Stratego Swat AI Analyzer
# Questo file assicura che Playwright sia installato correttamente

services:
  - type: web
    name: stratego-swat-ai
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    branch: main
    healthCheckPath: /
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /ms-playwright
      - key: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD
        value: "1"
      - key: NLTK_DATA
        value: /app/nltk_data
      - key: PYTHONPATH
        value: /app
      - key: STREAMLIT_SERVER_PORT
        value: "8501"
      - key: STREAMLIT_SERVER_ADDRESS
        value: "0.0.0.0"
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: "false"
      # Ottimizzazioni per velocità
      - key: STREAMLIT_SERVER_ENABLE_CORS
        value: "false"
      - key: STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION
        value: "false"
      - key: STREAMLIT_LOGGER_LEVEL
        value: "WARNING"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: PYTHONUNBUFFERED
        value: "1"
      # Cache per dipendenze
      - key: PIP_CACHE_DIR
        value: "/tmp/pip-cache"
      - key: DEPS_CACHE_ENABLED
        value: "true"
    buildCommand: |
      echo "🚀 Iniziando build per Render..."
      echo "📦 Installando dipendenze Python..."
      pip install --no-cache-dir -r requirements.txt
      echo "🌐 Installando browser Playwright..."
      playwright install chromium
      playwright install-deps chromium
      echo "✅ Build completato con successo"
    startCommand: |
      echo "🎯 Avviando Stratego Swat AI Analyzer..."
      streamlit run streamlit_app.py --server.port=8501 --server.address=0.0.0.0 --server.headless=true